export const FETCH_ALL_TABLES = 'FETCH_ALL_TABLES';
export const FETCH_TABLE_CONTENT = 'FETCH_TABLE_CONTENT';
export const SOFT_DELETE_SELECTION = 'DELETE_SELECTION';
export const RESTORE = 'RESTORE';
export const UNPUBLISH = 'UNPUBLISH';
export const PUBLISH = 'PUBLISH';
export const GET_FORM = 'GET_FORM';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
